language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env: 
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.2.*

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini || true
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}

install: composer update --prefer-dist

script: vendor/bin/phpunit

notifications:
  email:
    - damien.matabon@gmail.com
