language: php

php:
  - 7.2
  - 7.3
  - 7.4

env: 
  - SYMFONY_VERSION=^4.4
  - SYMFONY_VERSION=^5.2

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini || true
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}

install: COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist

script: vendor/bin/simple-phpunit

notifications:
  email:
    - damien.matabon@gmail.com
